 var MongoClient = require('mongodb').MongoClient;
var url = "mongodb://localhost:27017/";

MongoClient.connect(url, function(err, db) {
  if (err) throw err;
  var dbo = db.db("final");
  var myobj = [
    { searchID: 'sim', gameName: 'The Sims 4', description: 'Enjoy the power to create and control people in a virtual world where there are no rules.Express your creativity as you customize your Sims’ appearances and personalities, and build them the perfect homes. Develop your Sims’ relationships, pursue careers, and explore vibrant new worlds.', gamePrice: 49.99, company: 'EA', pictuer1: '../../assets/images/thesims4.jpg', picture2: '../../assets/images/thesims4.png', url: 'https://www.youtube.com/embed/DPXvlX9BAYQ'},
    { searchID: 'monster', gameName: 'Monster Hunter', description: 'The Monster Hunter (モンスターハンター Monsutā Hantā) franchise is a series of fantasy-themed action role-playing video games that started with the game Monster Hunter for PlayStation 2, released in 2004. Titles have been released across a variety of platforms, including personal computer, home console, portable consoles, and mobile devices. The series is developed and published by Capcom.', gamePrice: 49.99, company: 'Capcom', pictuer1: '../../assets/images/monster.jpg', picture2: '../../assets/images/monsterhunter1.jpg', url: 'https://www.youtube.com/embed/OotQrKEqe94'},
    { searchID: 'god', gameName: 'God of War', description: 'For the first time in the series, there are two main protagonists: Kratos, the former Greek God of War who remains as the only playable character, and his young son Atreus; at times, the player may passively control him. Following the death of Kratos" second wife and Atreus" mother, they journey to fulfill her promise to spread her ashes at the highest peak of the nine realms. Kratos keeps his troubled past a secret from Atreus, who is unaware of his divine nature. Along their journey, they encounter monsters and gods of the Norse world.', gamePrice: 49.99, company: 'Santa Monica Studio', pictuer1: '../../assets/images/godofwar.jpg', picture2: '../../assets/images/godofwar1.png', url: 'https://www.youtube.com/embed/K0u_kAWLJOA'},
    { searchID: 'evil', gameName: 'Resident Evil 2', description: 'The player controls Leon S Kennedy and Claire Redfield, who must escape Raccoon City after its citizens are transformed into zombies by a biological weapon two months after the events of the original Resident Evil. The gameplay focuses on exploration, puzzles, and combat; the main difference from its predecessor are the branching paths, with each player character having unique storylines and obstacles.', gamePrice: 49.99, company: 'Capcom', pictuer1: '../../assets/images/residentevil2.jpg', picture2: '../../assets/images/resident1.png', url: 'https://www.youtube.com/embed/KHaGZ4yamRM'},
    { searchID: 'devil', gameName: 'Devil May Cry 5', description: 'The gameplay will feature the return of Dante and Nero as playable characters, along with a new character,named "V".The gameplay is similar to the other titles in the Devil May Cry series, focusing on fast-paced "stylish action". The player fights off hordes of demons with a variety of attacks and weapons and receives a style-rating in combat based on a number of factors, such as move variety, the length of a combo and dodging attacks. The music in the game will change based on the player"s performance in combat.', gamePrice: 49.99, company: 'Capcom', pictuer1: '../../assets/images/devilmaycry5.png', picture2: '../../assets/images/devil1.jpg', url: 'https://www.youtube.com/embed/p2lWUQHUapM'},
    { searchID: 'dota', gameName: 'Dota2', description: 'Dota 2 is played in matches between two teams of five players, with each team occupying and defending their own separate base on the map. Each of the ten players independently controls a powerful character, known as a "hero", who all have unique abilities and differing styles of play. During a match, players collect experience points and items for their heroes to successfully defeat the opposing team is heroes in player versus player combat. A team wins by being the first to destroy a large structure located in the opposing team is base, called the "Ancient".', gamePrice: 49.99, company: 'Valve Corporation', pictuer1: '../../assets/images/dota2.jpg', picture2: '../../assets/images/dota1.jpg', url: 'https://www.youtube.com/embed/-cSFPIwMEq4'},
    { searchID: 'human', gameName: 'Human Fall Flat', description: 'Human: Fall Flat is a quirky open-ended physics-based puzzle platformer set in floating dreamscapes. Your goal is to find the exit of these surreal levels by solving puzzles with nothing but your wits. Local co-op for 2 players and up to 8 online for even more mayhem!', gamePrice: 7.15, company: 'Curve Digital', pictuer1: '../../assets/images/humanfallflat.jpg', picture2: '../../assets/images/humanfallflat2.jpg', url: 'https://www.youtube.com/embed/-Edk59BqSEU'},
    { searchID: 'minecraft', gameName: 'Minecraft: Story Mode', description: 'Together with old pals and new comrades alike, Jesse embarks on a brand new journey filled with tough choices, good times, and at least one temperamental llama.', gamePrice: 7.45, company: 'Telltale Games', pictuer1: '../../assets/images/minecraft.jpg', picture2: '../../assets/images/minecraft2.jpg', url: 'https://www.youtube.com/embed/Sb7D8APneOA'},
    { searchID: 'gujian', gameName: 'Gujian3', description: '"Gu Jian Qi Tan San: Meng Fu Qian Qiu Xing Ye" is a large 3D stand-alone role-playing game independently developed by Shanghai Chanlong, a subsidiary of Net Tang. This generation of works further expands the ancient sword world view, depicting the vast mountains and rivers in a realistic and beautiful style, and bringing the long-term humanity to the world with a new picture, bringing players closer to the real game world experience!', gamePrice: 14.75, company: 'Aurogon Info&Tech', pictuer1: '../../assets/images/gujian3.jpg', picture2: '../../assets/images/gujian32.jpg', url: 'https://www.youtube.com/embed/qnfhpYtfQ9w'},
    { searchID: 'elder', gameName: 'The Elder Scrolls V', description: 'The Elder Scrolls V: Skyrim is an action role-playing game, playable from either a first or third-person perspective. The player may freely roam over the land of Skyrim which is an open world environment consisting of wilderness expanses, dungeons, cities, towns, fortresses, and villages.', gamePrice: 19.25, company: 'Bethesda Softworks', pictuer1: '../../assets/images/theelderscrolls.jpg', picture2: '../../assets/images/theelderscrolls2.jpg', url: 'https://www.youtube.com/embed/JSRtYpNRoN0'},
    { searchID: 'isaac', gameName: 'The Binding of Isaac: Afterbirth', description: 'The Binding of Isaac: Rebirth is a randomly generated action RPG shooter with heavy Rogue-like elements. Following Isaac on his journey players will find bizarre treasures that change Isaac’s form giving him super human abilities and enabling him to fight off droves of mysterious creatures, discover secrets and fight his way to safety.', gamePrice: 6, company: 'Nicalis', pictuer1: '../../assets/images/bindingsaac.jpg', picture2: '../../assets/images/bindingsaac2.jpg', url: 'https://www.youtube.com/embed/_EWqWtED3MU'},
    { searchID: 'nba', gameName: 'NBA 2K19', description: 'NBA 2K celebrates 20 years of redefining what sports gaming can be. NBA 2K19 continues to push limits as it brings gaming one step closer to real-life basketball excitement and culture', gamePrice: 59.99, company: '2K Sports', pictuer1: '../../assets/images/nba2k19.jpg', picture2: '../../assets/images/NBA2K192.jpg', url: 'https://www.youtube.com/embed/Mre6zeJ4o_k'},
    { searchID: 'cook', gameName: 'Overcooked2', description: 'Overcooked returns with a brand-new helping of chaotic cooking action! Journey back to the Onion Kingdom and assemble your team of chefs in classic couch co-op or online play for up to four players. Hold onto your aprons… it’s time to save the world again!', gamePrice: 24.99, company: 'Team17 Digital Ltd', pictuer1: '../../assets/images/overcook.jpg', picture2: '../../assets/images/overcook.jpg', url: 'https://www.youtube.com/embed/ZKNO0MsDV2k'},
    { searchID: 'pubg', gameName: 'PUBG', description: 'PlayerUnknown is Battlegrounds (PUBG) is an online multiplayer battle royale game developed and published by PUBG Corporation, a subsidiary of South Korean video game company Bluehole. In the game, up to one hundred players parachute onto an island and scavenge for weapons and equipment to kill others while avoiding getting killed themselves. The available safe area of the game is map decreases in size over time, directing surviving players into tighter areas to force encounters. The last player or team standing wins the round.', gamePrice: 29.99, company: 'PUBG Corporation', pictuer1: '../../assets/images/pubg.jpeg', picture2: '../../assets/images/pubg.jpeg', url: 'https://www.youtube.com/embed/4rG9noTfb4A'},
    { searchID: 'starve', gameName: 'Do not Starve Together', description: 'Do not Starve is an open world survival video game developed by the Canadian indie company Klei Entertainment.The game follows a scientist named Wilson who finds himself in a dark, dreary world and must survive as long as possible. To this end, the player must keep Wilson healthy, fed, and mentally stable as he avoids a variety of surreal and supernatural enemies that will try to kill and devour him. The game is Adventure mode adds depth to the sparse plot and pits Wilson against the game is antagonist, Maxwell.', gamePrice: 14.99, company: 'Klei Entertainment', pictuer1: '../../assets/images/dontstarve.png', picture2: '../../assets/images/dontstarve.png', url: 'https://www.youtube.com/embed/bVbyn7c1X6E'},
    { searchID: 'chinese', gameName: 'Chinese Parents', description: 'Chinese Parents" is a simulation game developed by the squid play studio and released by Coconut Island. The player plays a child born in an ordinary Chinese family in the game.', gamePrice: 9.99, company: 'Coconut Island Games', pictuer1: '../../assets/images/chinesep.jpeg', picture2: '../../assets/images/chinesep.jpeg', url: 'https://www.youtube.com/embed/QKySu_iY9mI'},
    { searchID: 'fifa', gameName: 'FIFA 19', description: 'Build your dream squad and be part of the most popular mode in FIFA. ', gamePrice: 29.99, company: 'Electronic Arts', pictuer1: '../../assets/images/fifa.jpg', picture2: '../../assets/images/fifa.jpg', url: 'https://www.youtube.com/embed/zX0AV6yxyrQ'},
    { searchID: 'creed', gameName: 'Assassin Creed Odyssey', description: 'Choose your fate in Assassin Creed® Odyssey. From outcast to living legend, embark on an odyssey to uncover the secrets of your past and change the fate of Ancient Greece.', gamePrice: 59.99, company: 'Ubisoft', pictuer1: "../../assets/images/Assassin's creed.jpg", picture2: "../../assets/images/Assassin's creed.jpg", url: 'https://www.youtube.com/embed/ACZpHzBKCqU'},
    { searchID: 'red', gameName: 'Red Dead Redemption 2', description: 'America, 1899. The end of the Wild West era has begun. After a robbery goes badly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive. As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him.', gamePrice: 39.99, company: 'Rockstar Games', pictuer1: '../../assets/images/reddead.jpg', picture2: '../../assets/images/reddead.jpg', url: 'https://www.youtube.com/embed/eaW0tYpxyp0'}
  ];
  dbo.collection("games").insertMany(myobj, function(err, res) {
    if (err) throw err;
    console.log("Number of documents inserted: " + res.insertedCount);
    db.close();
  });
});